name: veryf_app
description: Aplikasi untuk membantu memverifikasi foto nota sebelum diupload ke
  database perusahaan

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  google_fonts: ^2.3.1
  user_dataprovider:
    path: packages/user_dataprovider
  user_repository:
    path: packages/user_repository
  report_repository:
    path: packages/report_repository

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
